### ISSUE TITLE
A bug in sao

### ISSUE THREAD

**Issue by licaiguo** [OpenHEVC/openHEVC#23]
when I build the latest code from repo, the decoder crashes when the input bitstream enables sao. The root cause is that the  prototype of the function pointer and implementation is incompatible.

The prototype of function pointer of sao edge filter is 
void (*sao_edge_filter[2])(uint8_t *_dst, uint8_t *_src, ptrdiff_t _stride_dst, ptrdiff_t _stride_src,  struct SAOParams *sao, int *borders, int _width, int _height, int c_idx, uint8_t *vert_edge, uint8_t *horiz_edge, uint8_t *diag_edge);
while the C implementation's prototype is
static void FUNC(sao_edge_filter_1)(uint8_t *_dst, uint8_t *_src,
                                    ptrdiff_t stride, SAOParams *sao,
                                    int *borders, int _width, int _height,
                                    int c_idx, uint8_t *vert_edge,
                                    uint8_t *horiz_edge, uint8_t *diag_edge)

**Comment by mraulet** [comment]
right! I will fix it. I forgot to merge some changes in the C version of the SAO. It works in branch shm6.1.

I'll fix it during the day.

Thanks!

----- Mail original -----
De: "Licai Guo" notifications@github.com
À: "OpenHEVC/openHEVC" openHEVC@noreply.github.com
Envoyé: Vendredi 7 Novembre 2014 04:07:35
Objet: [openHEVC] A bug in sao (#23)

when I build the latest code from repo, the decoder crashes when the input bitstream enables sao. The root cause is that the prototype of the function pointer and implementation is incompatible. 

The prototype of function pointer of sao edge filter is 
void (*sao_edge_filter[2])(uint8_t *_dst, uint8_t *_src, ptrdiff_t _stride_dst, ptrdiff_t _stride_src, struct SAOParams *sao, int *borders, int _width, int _height, int c_idx, uint8_t *vert_edge, uint8_t *horiz_edge, uint8_t *diag_edge); 
while the C implementation's prototype is 
static void FUNC(sao_edge_filter_1)(uint8_t *_dst, uint8_t *_src, 
ptrdiff_t stride, SAOParams *sao, 
int *borders, int _width, int _height, 
int c_idx, uint8_t *vert_edge, 
uint8_t *horiz_edge, uint8_t *diag_edge)

**Comment by mraulet** [comment]
fix in commit f4443a2d2ebbb3bc1785aedac767cc5f3c5ae2dd.
