### ISSUE TITLE
openHEVC does not work on Linux ?

### ISSUE THREAD

**Issue by fengxiujie** [OpenHEVC/openHEVC#41]
Hi, there,

   I tried to build & run openHEVC on my Linux machine. I could compile it successfully, However, I have problem with running the program, could any of you please help? 
   Here is my build & running steps:
1. 1. git clone git://github.com/OpenHEVC/openHEVC.git
2. 2. git checkout hevc_rext
3. 3. mkdir build
4. 4. cd build
5. 5. cmake -DCMAKE_BUILD_TYPE=RELEASE ..
6. 6. make
7. Run: ./hevc -i clip.265 -o test.yuv -n

However, I got result like this: 
"[hevc @ 0xade660] nb threads_frame = 1, nb threads_slice 1, thread_type = null 
[hevc @ 0xafbd00] nb threads_frame = 1, nb threads_slice 1, thread_type = null 
Video initialization failed: No available video device"

I searched log "Video initialization failed" in source code, it is located in function "Init_SDL()". So what should I do if I want to use openHEVC without SDL? Could any of you please help? Many thanks in advance!

**Comment by pcabarat** [comment]
Hi. 
I can't reproduce the issue.
As you said it must have something to do with SDL, or the bitstream you are trying to decode
Since your build generated hevc executable, I assume you have SDL installed on your computer (executable won't build otherwise, only the lib will be generated).
To the best of my knowledge there is currently no clean way of building hevc without SDL.
However you could try replace the USE_SDL preprocessor instruction by 0 in main_hm/main.c.

**Comment by fengxiujie** [comment]
Thanks Pcabarat! After “replace the USE_SDL preprocessor instruction by 0 in main_hm/main.c” and rebuild the whole openHEVC project again, I could run it successfully. Thanks again!
