### ISSUE TITLE
SHVC decoder mismatch

### ISSUE THREAD

**Issue by shhhhh79** [OpenHEVC/openHEVC#51]
Hello,
I'm testing the SHVC decoder on Linux.

With the latest code from hevc_rext branch, I get decoder mismatches for enh. layer frames.
Base layer is decoded fine(-l 0), but all enh. layer frames look broken(-l 1).
Tested shvc bitstreams were encoded with SHM4.1.

I verified that the w64 executable(openHEVC/bin/shvc/ffmpeg_w64/hevc_ffmpeg_w64.exe) has no problem with the same bitstreams on Windows.

Thank you!

**Comment by pcabarat** [comment]
Hi!
If you're interested in SHVC, you should have a look to HEVC_extensions branch. 
It should support 6.1 and higher  SHM versions. 

I don't know if it will support SHM-4.1 streams because of some changes made in the VPS.
If you're interested in 4.1 stream only, you might see an error (about VPS reserved 16 bits if I remember well) before resuming. In hevc_ps.c comment  the error return located right after the error report. The rest should work fine with a few warnings.

Based on what you said the SHVC support might be broken for some streams in hevc_rext.
The reason it works fine on windows, might be the w64 dll does not correspond to the hevc_rext branch build but an equivalent on our FFmpeg repo.

Pierre-Loup

**Comment by shhhhh79** [comment]
Hi.
I've been testing the code from HEVC_extensions branch and it is working fine with SHM 10 bitstreams.

Thanks :)
