### ISSUE TITLE
SHVC layer parsing

### ISSUE THREAD

**Issue by bayantaani** [OpenHEVC/openHEVC#61]
Hi all,
I'm sorry if this is not the right place to ask this but I don't know where else to ask, is there a way I can extract the layers from an SHVC encoded video? for example, to have the base layer in a file and the enhancement layer in a separate file.

**Comment by pcabarat** [comment]
Hi,
We do not plan to handle SHVC layers extraction. There is no simple way to do that.
You can have a look to the hevc parsing functions into libavcodec/h2645_parse.c an try to modify it in order ot copy the appropriate data into each of the files according to the NALU header layer_id.
However if you want something conformant you'll have to rewrite your own VPSs (base_layer_internal_flag , layers_dependencies  etc. ) for each file.
Please also note that SPSs and PPSs might be used by muliple layers, so you might have to read part of your slice headers to know he dependencies betwen parameter sets in order to know what needs to be included in each of your files.

**Comment by bayantaani** [comment]
I see. Thanks :)
I found something similar to what I want to achieve using MP4Box, it's in GPAC's demo on hybrid broadcast broadband streaming:
http://download.tsi.telecom-paristech.fr/gpac/demos_hybrid/
